#!/bin/bash

MY_HOME_DIR=$HOME

# bash history
> $MY_HOME_DIR/.bash_history

rm -rf $MY_HOME_DIR/.w3m/*
rm -f $MY_HOME_DIR/.local/share/recently-used.xbel
rm -f $MY_HOME_DIR/.recently-used
# mc
rm -rf $MY_HOME_DIR/.cache/mc/*
> $MY_HOME_DIR/.local/share/mc/history
# vim
> $MY_HOME_DIR/.viminfo
rm -f $MY_HOME_DIR/.cache/ctrlp/mru/cache.txt
# easytag
> $MY_HOME_DIR/.easytag/easytag.log
# fucking flash
rm -rf $MY_HOME_DIR/.adobe/
rm -rf $MY_HOME_DIR/.macromedia/
# ff
rm -rf $MY_HOME_DIR/.cache/mozilla/
# thumbnails
rm -rf $MY_HOME_DIR/.thumbnails/
# gthumb
> $MY_HOME_DIR/.config/gthumb/history.xbel
