#!/usr/bin/env bash

output=$(netstat -tupan 2>/dev/null | \
	grep LISTEN | \
	awk '
	{
		split($4, a, ":");
		split($7, p, "/");
		print "${color5}"p[1]"${color}",
		"${goto 50}${color4}"p[2]"${color}",
		"${goto 125}${color7}"a[1]"${color}",
		"${goto 200}${color8}"$1" ${color7}"a[2]"${color}";
	}
	'
)

if [[ -n "${output}" ]]; then
	echo '${color9}PID${goto 50}Name${goto 125}IP${goto 200}Port${color}'
	echo -n "${output}"
fi
